rh:
  build: .
  ports:
    - "8080:8080"
  environment:
    - MONGO_HOST=mongodb
  volumes:
    - /Users/mturatti/.m2:/root/.m2:rw
  links:
    - mongodb
mongodb:
  image: mongo:3.0
  ports:
    - 27017
